// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyTweak(arg1:string):Promise<void>;

export function DeleteFinding(arg1:string):Promise<void>;

export function DetectTweak(arg1:string):Promise<string>;

export function ListTweaks():Promise<Array<main.TweakDTO>>;

export function RevertTweak(arg1:string):Promise<void>;

export function StartScan():Promise<void>;
