// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTweak(arg1) {
  return window['go']['main']['App']['ApplyTweak'](arg1);
}

export function DeleteFinding(arg1) {
  return window['go']['main']['App']['DeleteFinding'](arg1);
}

export function DetectTweak(arg1) {
  return window['go']['main']['App']['DetectTweak'](arg1);
}

export function ListTweaks() {
  return window['go']['main']['App']['ListTweaks']();
}

export function RevertTweak(arg1) {
  return window['go']['main']['App']['RevertTweak'](arg1);
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}
